// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function getLargestElement(elements) {
  console.log(elements);
  var bestElement = /* None */0;
  var bestArea = 0;
  var elementsLength = elements.length;
  for(var i = 0 ,i_finish = elementsLength - 1 | 0; i <= i_finish; ++i){
    var element = Caml_array.caml_array_get(elements, i);
    var newArea = Caml_int32.imul(element.height, element.width);
    console.log(newArea);
    if (newArea > bestArea) {
      bestElement = /* Some */[element];
      bestArea = newArea;
    }
    
  }
  var match = bestElement;
  if (match) {
    return match[0];
  } else {
    return { };
  }
}

exports.getLargestElement = getLargestElement;
/* No side effect */
